name: Test Credential Helper

on:
  workflow_dispatch:
    inputs:
      custom_message:
        description: 'Custom message to display'
        required: false

jobs:
  set-credential-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set credential helper
        run: |
          git config --global credential.helper '!f() { echo "username=x-access-token"; echo "password=${{ github.token }}"; }; f'

      - name: Show .git/config
        run: cat .git/config

      - name: (Optional) Show custom message
        if: ${{ github.event.inputs.custom_message != '' }}
        run: echo "${{ github.event.inputs.custom_message }}"
