name: Test Credential Helper

on:
  workflow_dispatch:

jobs:
  set-credential-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set credential helper
        run: |
          git config --local credential.helper 'cache --timeout=300'
          echo -e "protocol=https\nhost=github.com\nusername=x-access-token\npassword=${{ github.token }}" | git credential approve

      - name: Security Audit
        run: |
          echo "=== Checking .git/config ==="
          cat .git/config

          echo "\n=== Checking ~/.gitconfig ==="
          cat ~/.gitconfig || echo "No ~/.gitconfig found"

          echo -e "\n=== Checking git remote URLs ==="
          git remote -v

          echo -e "\n=== Checking for credential files ==="
          find . -name "*credential*" -type f 2>/dev/null || echo "No credential files found"
        shell: bash
