name: Test Credential Helper

on:
  workflow_dispatch:

jobs:
  set-credential-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check for credential cache
        run: ps aux | grep "git/credential"
        shell: bash

      - name: Start credential cache daemon
        run: git credential-cache --timeout=300 daemon
        shell: bash

      - name: Configure temporary Git credentials
        run: |
          git credential-cache --timeout=300 store <<EOF
          protocol=https
          host=github.com
          username=x-access-token
          password=${{ github.token }}
          
          EOF
          git config --local credential.helper 'cache --timeout=300'

      - name: Re-check for credential cache
        run: ps aux | grep "git/credential"
        shell: bash

      - name: Security Audit
        run: |
          echo "=== Checking .git/config ==="
          cat .git/config

          echo "\n=== Checking ~/.gitconfig ==="
          cat ~/.gitconfig || echo "No ~/.gitconfig found"

          echo -e "\n=== Checking git remote URLs ==="
          git remote -v

          echo -e "\n=== Checking for credential files ==="
          find . -name "*credential*" -type f 2>/dev/null || echo "No credential files found"
        shell: bash
