name: Test Credential Helper

on:
  workflow_dispatch:

jobs:
  set-credential-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set credential helper
        run: |
          git config --global credential.helper '!f() { echo "username=x-access-token"; echo "password=${{ github.token }}"; }; f'

      - name: Show .git/config
        run: cat .git/config
